<#
.SYNOPSIS
    Measures Shodh's memory footprint and time to a usable window.

.DESCRIPTION
    Launches the given Shodh executable on a fresh, throwaway profile
    (SHODH_DATA_DIR in a temporary folder: never the user's own data) and
    samples the private memory of the app and every process it started
    (WebView2 browser, renderer, GPU and utility processes, the agent runtime,
    ...). Only the process tree rooted at the launched process is read; other
    Shodh instances on the machine are never enumerated, touched or stopped.

    Scenarios:
      idle    Start, wait for the window, idle -IdleSeconds.
      ingest  Start, wait for the window, index three small synthetic PDFs
              (generated by this script) through the same command the
              Library uses, then idle -IdleSeconds. No model is asked
              anything. Needs the search models (-ModelPath).

    Every scenario run gets a prime launch first (it creates the profile and
    the WebView2 user data; its time is reported as the cold start), then the
    measured launch on that profile. With -Runs N each scenario is measured N
    times and the summary is the median.

    Time to window: from launching the process to the frontend's
    `shodh:shell-mounted` performance mark (the sidebar, title bar and active
    view have committed to the DOM), read over the WebView2 DevTools protocol.
    The mark carries its own timestamp, so the polling interval does not
    affect the number.

    Memory: private bytes (commit charge, Win32_Process.PrivatePageCount) of
    each process, summed per group: core (the Shodh process), webview2,
    agent-runtime (omp), other. "Idle" is the median of the samples taken in
    the last half of the idle period; "peak" is the largest sample of the run.

.PARAMETER Exe
    The Shodh executable to measure (e.g. a release build).

.PARAMETER ModelPath
    Folder holding the search models (multilingual-e5-base/,
    ms-marco-MiniLM-L6-v2/), passed to the app as MODEL_PATH. Without it the
    app starts without search models and the ingest scenario cannot run.

.PARAMETER InstallModels
    When the search models are not in -ModelPath yet, have the app itself
    download and verify its pinned search models there first (Settings ->
    Search does the same). Used by CI to fill its model cache.

.PARAMETER WebViewArgsOverride
    WebView2 flags to measure with instead of the app's own (to compare
    flags; the DevTools port is added). Never used for the budget.

.PARAMETER BudgetIdleMB
    When above zero, exit with code 1 if the median idle total of the idle
    scenario exceeds it.

.PARAMETER BudgetWindowSeconds
    When above zero, exit with code 1 if the median time to window of the
    idle scenario exceeds it.

.EXAMPLE
    ./scripts/measure-footprint.ps1 -Exe C:\build\release\shodh-rag-app.exe -ModelPath D:\models -Output footprint.json
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$Exe,

    [string]$ModelPath,

    [ValidateSet('idle', 'ingest', 'all')]
    [string]$Scenario = 'all',

    [ValidateRange(1, 20)]
    [int]$Runs = 3,

    [ValidateRange(10, 3600)]
    [int]$IdleSeconds = 60,

    [ValidateRange(1, 60)]
    [int]$IntervalSeconds = 5,

    [ValidateRange(5, 600)]
    [int]$StartupTimeoutSeconds = 90,

    [ValidateRange(5, 3600)]
    [int]$IngestTimeoutSeconds = 600,

    [ValidateRange(1024, 65535)]
    [int]$CdpPort = 9339,

    [string]$Output,

    [double]$BudgetIdleMB = 0,

    [double]$BudgetWindowSeconds = 0,

    [switch]$KeepProfiles,

    [switch]$InstallModels,

    [string]$WebViewArgsOverride
)

Set-StrictMode -Version 3.0
$ErrorActionPreference = 'Stop'

$ExePath = (Resolve-Path -LiteralPath $Exe).Path
$ExeName = [System.IO.Path]::GetFileName($ExePath)
if ($InstallModels -and -not $ModelPath) {
    throw '-InstallModels needs -ModelPath (the folder to install the models into).'
}
if ($ModelPath) {
    if ($InstallModels) { New-Item -ItemType Directory -Force -Path $ModelPath | Out-Null }
    $ModelPath = (Resolve-Path -LiteralPath $ModelPath).Path
}
function Test-Models {
    if (-not $ModelPath) { return $false }
    $e5 = Join-Path $ModelPath 'multilingual-e5-base'
    [bool]((Test-Path -LiteralPath (Join-Path $e5 'tokenizer.json')) -and (Get-ChildItem -LiteralPath $e5 -Filter '*.onnx' -ErrorAction SilentlyContinue))
}

# WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS replaces the flags the app gives
# WebView2, so the app's own flags (WEBVIEW_BROWSER_ARGS in profile.rs, read
# from this checkout) are repeated next to the DevTools port.
$ProfileSource = Join-Path $PSScriptRoot '../app/src-tauri/src/profile.rs'
$AppWebViewArgs = [regex]::Match((Get-Content -Raw -LiteralPath $ProfileSource), 'WEBVIEW_BROWSER_ARGS: &str =\s*"([^"]+)"')
if (-not $AppWebViewArgs.Success) { throw "WEBVIEW_BROWSER_ARGS not found in $ProfileSource" }
$BaseWebViewArgs = if ($WebViewArgsOverride) { $WebViewArgsOverride } else { $AppWebViewArgs.Groups[1].Value }
$WebViewArgs = "$BaseWebViewArgs --remote-debugging-port=$CdpPort"
if ($WebViewArgsOverride -and ($BudgetIdleMB -gt 0 -or $BudgetWindowSeconds -gt 0)) {
    throw 'Budgets apply to the app as built: -WebViewArgsOverride cannot be combined with them.'
}

# Environment variables never passed to the measured app: provider keys and
# tokens of whoever runs this, and settings that would change what is measured.
$StrippedEnv = '(?i)(API_KEY|_TOKEN|_SECRET|PASSWORD|^SHODH_|^MODEL_PATH$|^WEBVIEW2_|^RUST_LOG$)'

function Get-EpochMs {
    [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()
}

function Get-Median([double[]]$Values) {
    if (-not $Values -or $Values.Count -eq 0) { return $null }
    $sorted = @($Values | Sort-Object)
    $n = $sorted.Count
    if ($n % 2 -eq 1) { return [double]$sorted[($n - 1) / 2] }
    return ([double]$sorted[$n / 2 - 1] + [double]$sorted[$n / 2]) / 2
}

function Get-Group([string]$Name) {
    if ($Name -ieq $ExeName) { return 'core' }
    if ($Name -ieq 'msedgewebview2.exe') { return 'webview2' }
    if ($Name -match '^(?i)omp') { return 'agent-runtime' }
    return 'other'
}

# The launched process and every process it started (recursively), created
# after it (a recycled parent id never pulls in an unrelated process).
function Get-ProcessTree([int]$RootId, [datetime]$RootStart) {
    $all = Get-CimInstance -ClassName Win32_Process -Property ProcessId, ParentProcessId, Name, PrivatePageCount, WorkingSetSize, CreationDate
    $byParent = @{}
    $root = $null
    foreach ($p in $all) {
        if ([int]$p.ProcessId -eq $RootId) { $root = $p; continue }
        $parent = [int]$p.ParentProcessId
        if (-not $byParent.ContainsKey($parent)) { $byParent[$parent] = New-Object System.Collections.ArrayList }
        [void]$byParent[$parent].Add($p)
    }
    if ($null -eq $root) { return @() }
    $tree = New-Object System.Collections.ArrayList
    [void]$tree.Add($root)
    $queue = New-Object System.Collections.Queue
    $queue.Enqueue([int]$RootId)
    while ($queue.Count -gt 0) {
        $id = $queue.Dequeue()
        if (-not $byParent.ContainsKey($id)) { continue }
        foreach ($child in $byParent[$id]) {
            if ($child.CreationDate -and $child.CreationDate -lt $RootStart.AddSeconds(-1)) { continue }
            [void]$tree.Add($child)
            $queue.Enqueue([int]$child.ProcessId)
        }
    }
    return $tree
}

function Get-Sample([int]$RootId, [datetime]$RootStart, [long]$LaunchMs) {
    $tree = @(Get-ProcessTree $RootId $RootStart)
    $groups = [ordered]@{ 'core' = 0.0; 'webview2' = 0.0; 'agent-runtime' = 0.0; 'other' = 0.0 }
    $counts = [ordered]@{ 'core' = 0; 'webview2' = 0; 'agent-runtime' = 0; 'other' = 0 }
    $others = New-Object System.Collections.ArrayList
    $workingSet = 0.0
    foreach ($p in $tree) {
        $group = Get-Group $p.Name
        $groups[$group] += [double]$p.PrivatePageCount / 1MB
        $counts[$group] += 1
        $workingSet += [double]$p.WorkingSetSize / 1MB
        if ($group -eq 'other') { [void]$others.Add($p.Name) }
    }
    $total = 0.0
    foreach ($v in $groups.Values) { $total += $v }
    $rounded = [ordered]@{}
    foreach ($k in $groups.Keys) { $rounded[$k] = [math]::Round($groups[$k], 1) }
    [pscustomobject][ordered]@{
        tSeconds       = [math]::Round(((Get-EpochMs) - $LaunchMs) / 1000.0, 1)
        totalMB        = [math]::Round($total, 1)
        workingSetMB   = [math]::Round($workingSet, 1)
        groupsMB       = $rounded
        processCounts  = $counts
        otherProcesses = @($others | Sort-Object -Unique)
        alive          = ($tree.Count -gt 0)
    }
}

# --- DevTools protocol (WebView2 remote debugging) ---------------------------

function Get-PageSocketUrl {
    try {
        $targets = Invoke-RestMethod -Uri "http://127.0.0.1:$CdpPort/json/list" -TimeoutSec 2 -UseBasicParsing
    } catch {
        return $null
    }
    $page = @($targets | Where-Object { $_.type -eq 'page' -and $_.url -notmatch '^(devtools|about:)' }) | Select-Object -First 1
    if ($null -eq $page) { return $null }
    return $page.webSocketDebuggerUrl
}

function Connect-Cdp([string]$Url) {
    $socket = New-Object System.Net.WebSockets.ClientWebSocket
    [void]$socket.ConnectAsync([Uri]$Url, [Threading.CancellationToken]::None).GetAwaiter().GetResult()
    return [pscustomobject]@{ Socket = $socket; NextId = 1 }
}

function Close-Cdp($Cdp) {
    if ($null -eq $Cdp) { return }
    try {
        [void]$Cdp.Socket.CloseAsync([System.Net.WebSockets.WebSocketCloseStatus]::NormalClosure, '', [Threading.CancellationToken]::None).GetAwaiter().GetResult()
    } catch {
        # The app may already be gone.
    }
    $Cdp.Socket.Dispose()
}

# Evaluate a JavaScript expression in the page and return its value.
function Invoke-PageScript($Cdp, [string]$Expression, [int]$TimeoutSeconds = 10) {
    $id = $Cdp.NextId
    $Cdp.NextId = $id + 1
    $request = @{
        id     = $id
        method = 'Runtime.evaluate'
        params = @{ expression = $Expression; awaitPromise = $true; returnByValue = $true }
    } | ConvertTo-Json -Depth 5 -Compress
    $bytes = [Text.Encoding]::UTF8.GetBytes($request)
    $segment = New-Object 'System.ArraySegment[byte]' -ArgumentList @(, $bytes)
    [void]$Cdp.Socket.SendAsync($segment, [System.Net.WebSockets.WebSocketMessageType]::Text, $true, [Threading.CancellationToken]::None).GetAwaiter().GetResult()

    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    $buffer = New-Object byte[] 65536
    while ((Get-Date) -lt $deadline) {
        $message = New-Object System.IO.MemoryStream
        do {
            $receiveSegment = New-Object 'System.ArraySegment[byte]' -ArgumentList @(, $buffer)
            $cts = New-Object Threading.CancellationTokenSource
            $cts.CancelAfter([math]::Max(100, [int]($deadline - (Get-Date)).TotalMilliseconds))
            $result = $Cdp.Socket.ReceiveAsync($receiveSegment, $cts.Token).GetAwaiter().GetResult()
            $message.Write($buffer, 0, $result.Count)
        } while (-not $result.EndOfMessage)
        $reply = [Text.Encoding]::UTF8.GetString($message.ToArray()) | ConvertFrom-Json
        if ($reply.PSObject.Properties['id'] -and $reply.id -eq $id) {
            if ($reply.PSObject.Properties['error']) { throw "DevTools error: $($reply.error.message)" }
            if ($reply.result.PSObject.Properties['exceptionDetails']) {
                throw "Page script failed: $($reply.result.exceptionDetails.text)"
            }
            if ($reply.result.result.PSObject.Properties['value']) { return $reply.result.result.value }
            return $null
        }
    }
    throw "DevTools did not answer within $TimeoutSeconds s"
}

# Startup marks (epoch ms) recorded by app/src/lib/startupTiming.ts.
$MarksScript = @'
(() => {
  const at = name => {
    const m = performance.getEntriesByName('shodh:' + name, 'mark')[0];
    return m ? performance.timeOrigin + m.startTime : null;
  };
  return JSON.stringify({
    shellMounted: at('shell-mounted'),
    indexReady: at('index-ready'),
    conversationsLoaded: at('conversations-loaded'),
  });
})()
'@

# --- Synthetic fixtures --------------------------------------------------------

# A one-page PDF with the given lines in Helvetica (written by hand: no
# dependencies, nothing copyrighted).
function New-FixturePdf([string]$Path, [string[]]$Lines) {
    $escaped = $Lines | ForEach-Object { $_.Replace('\', '\\').Replace('(', '\(').Replace(')', '\)') }
    $content = New-Object System.Text.StringBuilder
    [void]$content.Append("BT /F1 11 Tf 14 TL 72 720 Td`n")
    foreach ($line in $escaped) { [void]$content.Append("($line) Tj T*`n") }
    [void]$content.Append("ET")
    $stream = $content.ToString()
    $objects = @(
        '<< /Type /Catalog /Pages 2 0 R >>',
        '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
        '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
        '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>',
        "<< /Length $([Text.Encoding]::ASCII.GetByteCount($stream)) >>`nstream`n$stream`nendstream"
    )
    $pdf = New-Object System.Text.StringBuilder
    [void]$pdf.Append("%PDF-1.4`n")
    $offsets = New-Object System.Collections.ArrayList
    for ($i = 0; $i -lt $objects.Count; $i++) {
        [void]$offsets.Add([Text.Encoding]::ASCII.GetByteCount($pdf.ToString()))
        [void]$pdf.Append("$($i + 1) 0 obj`n$($objects[$i])`nendobj`n")
    }
    $xref = [Text.Encoding]::ASCII.GetByteCount($pdf.ToString())
    [void]$pdf.Append("xref`n0 $($objects.Count + 1)`n0000000000 65535 f `n")
    foreach ($offset in $offsets) { [void]$pdf.Append(('{0:D10} 00000 n `n' -f $offset)) }
    [void]$pdf.Append("trailer`n<< /Size $($objects.Count + 1) /Root 1 0 R >>`nstartxref`n$xref`n%%EOF`n")
    [IO.File]::WriteAllBytes($Path, [Text.Encoding]::ASCII.GetBytes($pdf.ToString()))
}

function New-Fixtures([string]$Folder) {
    New-Item -ItemType Directory -Force -Path $Folder | Out-Null
    $topics = @(
        @{ name = 'tide-pools'; title = 'Field Notes on Tide Pool Ecology'; subject = 'tide pools'; detail = 'Sea stars, anemones and barnacles share each rock shelf, and the pools are mapped at every low tide.' },
        @{ name = 'bridge-loads'; title = 'A Short Study of Footbridge Loads'; subject = 'footbridges'; detail = 'Deck sway is measured under walking crowds, and the damping of each span is compared with its design value.' },
        @{ name = 'sourdough'; title = 'Fermentation Timing in Sourdough Starters'; subject = 'sourdough starters'; detail = 'Rise height is logged every hour at three kitchen temperatures, with the flour and water ratio held fixed.' }
    )
    foreach ($topic in $topics) {
        $lines = New-Object System.Collections.ArrayList
        [void]$lines.Add($topic.title)
        [void]$lines.Add('')
        for ($section = 1; $section -le 4; $section++) {
            [void]$lines.Add("Section $section")
            [void]$lines.Add("This synthetic document describes $($topic.subject) for a footprint measurement.")
            [void]$lines.Add($topic.detail)
            [void]$lines.Add("Observation $section records how the measurements changed over the week.")
            [void]$lines.Add("The method in section $section is repeated three times and the results agree.")
            [void]$lines.Add('')
        }
        New-FixturePdf -Path (Join-Path $Folder "$($topic.name).pdf") -Lines $lines
    }
}

# --- Launch and measure ----------------------------------------------------------

function Start-Shodh([string]$ProfileDir) {
    # The app inherits this process's environment: set the measured
    # environment here for the launch and put everything back after.
    $saved = @{}
    foreach ($item in @(Get-ChildItem Env:)) {
        if ($item.Name -match $StrippedEnv) {
            $saved[$item.Name] = $item.Value
            Remove-Item -LiteralPath "Env:$($item.Name)"
        }
    }
    $logDir = Split-Path -Parent $ProfileDir
    try {
        $env:SHODH_DATA_DIR = $ProfileDir
        $env:WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS = $WebViewArgs
        if ($ModelPath) { $env:MODEL_PATH = $ModelPath }
        $launchMs = Get-EpochMs
        $process = Start-Process -FilePath $ExePath -WorkingDirectory ([IO.Path]::GetDirectoryName($ExePath)) -PassThru `
            -RedirectStandardOutput (Join-Path $logDir ("app-{0}.log" -f $launchMs)) -RedirectStandardError (Join-Path $logDir ("app-{0}.err.log" -f $launchMs))
    } finally {
        foreach ($name in 'SHODH_DATA_DIR', 'WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS', 'MODEL_PATH') {
            Remove-Item -LiteralPath "Env:$name" -ErrorAction SilentlyContinue
        }
        foreach ($name in $saved.Keys) { Set-Item -LiteralPath "Env:$name" -Value $saved[$name] }
    }
    [pscustomobject]@{ Process = $process; LaunchMs = $launchMs; Start = $process.StartTime; LogDir = $logDir }
}

function Stop-Shodh($App) {
    $rootId = $App.Process.Id
    $tree = @(Get-ProcessTree $rootId $App.Start)
    & taskkill.exe /PID $rootId /T /F 2>&1 | Out-Null
    $deadline = (Get-Date).AddSeconds(20)
    foreach ($p in $tree) {
        while ((Get-Date) -lt $deadline -and (Get-Process -Id ([int]$p.ProcessId) -ErrorAction SilentlyContinue)) {
            Start-Sleep -Milliseconds 200
        }
        $left = Get-Process -Id ([int]$p.ProcessId) -ErrorAction SilentlyContinue
        if ($left -and $left.StartTime -ge $App.Start.AddSeconds(-1)) { Stop-Process -Id $left.Id -Force -ErrorAction SilentlyContinue }
    }
}

# Wait for the shell-mounted mark. Returns the marks (ms after launch) and the
# DevTools connection, sampling memory every second meanwhile.
function Wait-Window($App, [System.Collections.ArrayList]$Samples) {
    $deadline = (Get-Date).AddSeconds($StartupTimeoutSeconds)
    $cdp = $null
    while ((Get-Date) -lt $deadline) {
        if ($App.Process.HasExited) { throw "Shodh exited during startup (code $($App.Process.ExitCode))" }
        [void]$Samples.Add((Get-Sample $App.Process.Id $App.Start $App.LaunchMs))
        if ($null -eq $cdp) {
            $url = Get-PageSocketUrl
            if ($url) { $cdp = Connect-Cdp $url }
        }
        if ($null -ne $cdp) {
            $marks = (Invoke-PageScript $cdp $MarksScript) | ConvertFrom-Json
            if ($null -ne $marks.shellMounted) {
                $relative = [ordered]@{}
                foreach ($name in 'shellMounted', 'indexReady', 'conversationsLoaded') {
                    $value = $marks.$name
                    $relative[$name] = if ($null -eq $value) { $null } else { [math]::Round(([double]$value - $App.LaunchMs) / 1000.0, 3) }
                }
                return [pscustomobject]@{ Cdp = $cdp; Marks = $relative }
            }
        }
        Start-Sleep -Milliseconds 250
    }
    Close-Cdp $cdp
    throw "No usable window within $StartupTimeoutSeconds s"
}

function Invoke-Idle($App, [System.Collections.ArrayList]$Samples, [string]$Phase) {
    $start = Get-Date
    $idle = New-Object System.Collections.ArrayList
    while (((Get-Date) - $start).TotalSeconds -lt $IdleSeconds) {
        Start-Sleep -Seconds $IntervalSeconds
        if ($App.Process.HasExited) { throw "Shodh exited while idle (code $($App.Process.ExitCode))" }
        $sample = Get-Sample $App.Process.Id $App.Start $App.LaunchMs
        $sample | Add-Member -NotePropertyName phase -NotePropertyValue $Phase
        $sample | Add-Member -NotePropertyName idleSeconds -NotePropertyValue ([math]::Round(((Get-Date) - $start).TotalSeconds, 1))
        [void]$Samples.Add($sample)
        [void]$idle.Add($sample)
    }
    # Steady state: the second half of the idle period.
    $steady = @($idle | Where-Object { $_.idleSeconds -ge $IdleSeconds / 2 })
    if ($steady.Count -eq 0) { $steady = @($idle) }
    $groups = [ordered]@{}
    foreach ($g in 'core', 'webview2', 'agent-runtime', 'other') {
        $groups[$g] = [math]::Round((Get-Median @($steady | ForEach-Object { [double]$_.groupsMB[$g] })), 1)
    }
    [pscustomobject][ordered]@{
        totalMB  = [math]::Round((Get-Median @($steady | ForEach-Object { [double]$_.totalMB })), 1)
        groupsMB = $groups
    }
}

function Get-Peak([System.Collections.ArrayList]$Samples) {
    $groups = [ordered]@{}
    foreach ($g in 'core', 'webview2', 'agent-runtime', 'other') {
        $groups[$g] = [math]::Round(($Samples | ForEach-Object { [double]$_.groupsMB[$g] } | Measure-Object -Maximum).Maximum, 1)
    }
    [pscustomobject][ordered]@{
        totalMB  = [math]::Round(($Samples | ForEach-Object { [double]$_.totalMB } | Measure-Object -Maximum).Maximum, 1)
        groupsMB = $groups
    }
}

function Invoke-Ingest($App, $Cdp, [string]$Folder, [System.Collections.ArrayList]$Samples) {
    $invokeArgs = @{
        folderPath = $Folder
        spaceId    = 'footprint-fixtures'
        options    = @{ skip_indexed = $false; watch_changes = $false; process_subdirs = $false; priority = 'normal'; file_types = @() }
    } | ConvertTo-Json -Depth 5 -Compress
    $startScript = @"
(() => {
  window.__shodhFootprint = { done: false };
  window.__TAURI_INTERNALS__.invoke('link_folder_enhanced', $invokeArgs).then(
    r => { window.__shodhFootprint = { done: true, ok: true, result: r }; },
    e => { window.__shodhFootprint = { done: true, ok: false, error: String(e) }; });
  return true;
})()
"@
    [void](Invoke-PageScript $Cdp $startScript)
    $started = Get-Date
    while (((Get-Date) - $started).TotalSeconds -lt $IngestTimeoutSeconds) {
        Start-Sleep -Seconds 1
        $sample = Get-Sample $App.Process.Id $App.Start $App.LaunchMs
        $sample | Add-Member -NotePropertyName phase -NotePropertyValue 'ingest'
        [void]$Samples.Add($sample)
        $state = (Invoke-PageScript $Cdp 'JSON.stringify(window.__shodhFootprint)') | ConvertFrom-Json
        if ($state.done) {
            if (-not $state.ok) { throw "Indexing the fixtures failed: $($state.error)" }
            if ($state.result.files_processed -lt 3) {
                throw "Only $($state.result.files_processed) of 3 fixtures were indexed: $($state.result.failures | ConvertTo-Json -Compress)"
            }
            return [pscustomobject][ordered]@{
                seconds        = [math]::Round(((Get-Date) - $started).TotalSeconds, 1)
                filesProcessed = $state.result.files_processed
                chunks         = $state.result.total_chunks
            }
        }
    }
    throw "Indexing the fixtures did not finish within $IngestTimeoutSeconds s"
}

# Models the app loaded during the measured launch (lazy_model's log line).
function Get-ModelLoads($App) {
    $log = Get-ChildItem -LiteralPath $App.LogDir -Filter ("app-{0}*.log" -f $App.LaunchMs) -ErrorAction SilentlyContinue
    foreach ($file in $log) {
        foreach ($line in (Get-Content -LiteralPath $file.FullName -ErrorAction SilentlyContinue)) {
            $plain = $line -replace "$([char]27)\[[0-9;]*m", ''
            if ($plain -match 'Model loaded on first use' -and $plain -match 'model="?([\w-]+)"?') { $Matches[1] }
        }
    }
}

function Remove-Folder([string]$Path) {
    if ($KeepProfiles -or -not (Test-Path -LiteralPath $Path)) { return }
    for ($i = 0; $i -lt 10; $i++) {
        try {
            Remove-Item -LiteralPath $Path -Recurse -Force
            return
        } catch {
            Start-Sleep -Milliseconds 500
        }
    }
    Write-Warning "Could not remove $Path"
}

function Invoke-Run([string]$Kind, [int]$Index) {
    $work = Join-Path ([IO.Path]::GetTempPath()) ("shodh-footprint-" + [guid]::NewGuid().ToString('N'))
    $profileDir = Join-Path $work 'profile'
    New-Item -ItemType Directory -Force -Path $profileDir | Out-Null
    try {
        # Prime launch: creates the profile and the WebView2 user data.
        $prime = Start-Shodh $profileDir
        $primeSamples = New-Object System.Collections.ArrayList
        try {
            $primeWindow = Wait-Window $prime $primeSamples
            Close-Cdp $primeWindow.Cdp
        } finally {
            Stop-Shodh $prime
        }

        $app = Start-Shodh $profileDir
        $samples = New-Object System.Collections.ArrayList
        try {
            $window = Wait-Window $app $samples
            $ingest = $null
            try {
                if ($Kind -eq 'ingest') {
                    $fixtures = Join-Path $work 'fixtures'
                    New-Fixtures $fixtures
                    $ingest = Invoke-Ingest $app $window.Cdp $fixtures $samples
                }
                $idle = Invoke-Idle $app $samples 'idle'
            } finally {
                Close-Cdp $window.Cdp
            }
        } finally {
            Stop-Shodh $app
        }
        $modelLoads = @(Get-ModelLoads $app)
        Write-Host ("{0} run {1}: window {2:N2} s, idle {3:N1} MB (core {4:N1}, webview2 {5:N1}, agent-runtime {6:N1}, other {7:N1})" -f `
                $Kind, $Index, $window.Marks.shellMounted, $idle.totalMB, $idle.groupsMB['core'], $idle.groupsMB['webview2'], $idle.groupsMB['agent-runtime'], $idle.groupsMB['other'])
        [pscustomobject][ordered]@{
            scenario               = $Kind
            run                    = $Index
            coldWindowSeconds      = $primeWindow.Marks.shellMounted
            windowSeconds          = $window.Marks.shellMounted
            marksSeconds           = $window.Marks
            ingest                 = $ingest
            idle                   = $idle
            peak                   = Get-Peak $samples
            modelLoads             = $modelLoads
            samples                = $samples
        }
    } finally {
        Remove-Folder $work
    }
}

function Get-Summary([object[]]$RunResults) {
    $groups = [ordered]@{}
    foreach ($g in 'core', 'webview2', 'agent-runtime', 'other') {
        $groups[$g] = [ordered]@{
            idleMB = [math]::Round((Get-Median @($RunResults | ForEach-Object { [double]$_.idle.groupsMB[$g] })), 1)
            peakMB = [math]::Round((Get-Median @($RunResults | ForEach-Object { [double]$_.peak.groupsMB[$g] })), 1)
        }
    }
    [pscustomobject][ordered]@{
        runs                    = $RunResults.Count
        windowSecondsMedian     = [math]::Round((Get-Median @($RunResults | ForEach-Object { [double]$_.windowSeconds })), 3)
        coldWindowSecondsMedian = [math]::Round((Get-Median @($RunResults | ForEach-Object { [double]$_.coldWindowSeconds })), 3)
        idleTotalMBMedian       = [math]::Round((Get-Median @($RunResults | ForEach-Object { [double]$_.idle.totalMB })), 1)
        peakTotalMBMedian       = [math]::Round((Get-Median @($RunResults | ForEach-Object { [double]$_.peak.totalMB })), 1)
        groups                  = $groups
    }
}

# Launch the app on a throwaway profile with MODEL_PATH = -ModelPath and run
# its own `install_search_models` (pinned URLs, SHA-256 checked).
function Install-SearchModels {
    $work = Join-Path ([IO.Path]::GetTempPath()) ("shodh-footprint-" + [guid]::NewGuid().ToString('N'))
    $profileDir = Join-Path $work 'profile'
    New-Item -ItemType Directory -Force -Path $profileDir | Out-Null
    try {
        $app = Start-Shodh $profileDir
        $samples = New-Object System.Collections.ArrayList
        try {
            $window = Wait-Window $app $samples
            try {
                Write-Host "Installing the search models into $ModelPath"
                $result = Invoke-PageScript $window.Cdp "window.__TAURI_INTERNALS__.invoke('install_search_models').then(r => JSON.stringify(r))" 3600
                Write-Host "Search models installed: $result"
            } finally {
                Close-Cdp $window.Cdp
            }
        } finally {
            Stop-Shodh $app
        }
    } finally {
        Remove-Folder $work
    }
}

# --- Main --------------------------------------------------------------------------

if ($InstallModels -and -not (Test-Models)) { Install-SearchModels }
$ModelsPresent = Test-Models
if ($Scenario -ne 'idle' -and -not $ModelsPresent) {
    throw "The ingest scenario needs the search models: pass -ModelPath with a multilingual-e5-base folder (or -InstallModels), or -Scenario idle."
}

$scenarios = if ($Scenario -eq 'all') { @('idle', 'ingest') } else { @($Scenario) }
$results = [ordered]@{}
foreach ($kind in $scenarios) {
    $runResults = New-Object System.Collections.ArrayList
    for ($i = 1; $i -le $Runs; $i++) {
        [void]$runResults.Add((Invoke-Run $kind $i))
    }
    $results[$kind] = [ordered]@{ summary = Get-Summary $runResults; runs = $runResults }
}

$os = Get-CimInstance -ClassName Win32_OperatingSystem -Property Caption, Version, TotalVisibleMemorySize
$cpu = Get-CimInstance -ClassName Win32_Processor -Property Name, NumberOfLogicalProcessors | Select-Object -First 1
$report = [ordered]@{
    measuredAt          = (Get-Date).ToUniversalTime().ToString('o')
    exe                 = $ExePath
    exeBytes            = (Get-Item -LiteralPath $ExePath).Length
    modelsPresent       = $ModelsPresent
    machine             = [ordered]@{
        os          = "$($os.Caption) $($os.Version)"
        memoryGB    = [math]::Round([double]$os.TotalVisibleMemorySize / 1MB, 1)
        cpu         = $cpu.Name
        logicalCpus = $cpu.NumberOfLogicalProcessors
    }
    definitions         = [ordered]@{
        memory = 'Private bytes (commit) of the launched process and all its descendants, in MB; idle = median of the samples in the second half of the idle period; peak = largest sample of the run; summaries are medians over runs.'
        window = 'Seconds from process launch to the shodh:shell-mounted performance mark (shell committed to the DOM), on a profile created by a prime launch; cold = the prime launch itself.'
    }
    settings            = [ordered]@{ runs = $Runs; idleSeconds = $IdleSeconds; intervalSeconds = $IntervalSeconds; webViewArgs = $WebViewArgs }
    scenarios           = $results
}
$json = $report | ConvertTo-Json -Depth 12
if ($Output) {
    [IO.File]::WriteAllText($Output, $json, (New-Object System.Text.UTF8Encoding($false)))
    Write-Host "Report written to $Output"
} else {
    $json
}

$failures = New-Object System.Collections.ArrayList
if ($results.Contains('idle')) {
    $summary = $results['idle'].summary
    if ($BudgetIdleMB -gt 0 -and $summary.idleTotalMBMedian -gt $BudgetIdleMB) {
        [void]$failures.Add("idle memory $($summary.idleTotalMBMedian) MB is over the $BudgetIdleMB MB budget")
    }
    if ($BudgetWindowSeconds -gt 0 -and $summary.windowSecondsMedian -gt $BudgetWindowSeconds) {
        [void]$failures.Add("time to window $($summary.windowSecondsMedian) s is over the $BudgetWindowSeconds s budget")
    }
}
if ($failures.Count -gt 0) {
    foreach ($f in $failures) { Write-Host "BUDGET EXCEEDED: $f" }
    exit 1
}
